### ISSUE TITLE
Project file structure is not up to standard and should be changed

### ISSUE THREAD

**Issue by kortla-dev** [zag-prj/zag-frontend#2]
The current structure of the public directory needs to be improved. We shouldn’t have a separate directory for every single HTML page. Instead, all HTML files should be grouped together in one directory, all CSS files in another, and all other assets like images in a separate folder. This way, the directory will be better organized without unnecessary separation for each page.

e.g.
- public/
  - index.html
  - about.html
  - contact.html
  - services.html
  - css/
    - main.css
    - about.css
    - contact.css
  - assets/
    - images/
      - logo.png
      - header.jpg
    - scripts/
      - main.js
      - analytics.js

**Comment by MistaWasabi** [comment]
fixed pushed it under new name FixedEMPUI
