### ISSUE TITLE
Remove unused files and switch to the changes done in #2

### ISSUE THREAD

**Issue by kortla-dev** [zag-prj/zag-frontend#6]
- empty `public/` and move the contents of `views/FixedEmpUI/` to `public/`
- remove all files that are not being use otherwise comment on this issue explaining why we should keep them
- make sure everything is working as intended

P.S. Do not close the issue when you are done; I will review the changes and close it if I am satisfied with the results.

**Comment by MistaWasabi** [comment]
hopefully this is up to your standard
